id: P4ADC60FD
initial_creation_type: input
source_metadata:
  title: Pedagogy Series
  language: bo
  description: 'The following texts are available as part of our Pedagogy series on
    the theory and method of Dharma discourse:'
  volume:
    9d0cf0ab389c41fc875e121b101b0695:
      title: Notes from Miscellaneous Writings
      parent: General
    90a798a4741b4f13b71e515888bf7dbc:
      title: Preliminary Points to be Explained When Teaching the Buddha's Word or
        the Treatises
      parent: General
    1673169f41824e819ff1ade17b39f062:
      title: Prologue to Abhisamayālaṃkāra Commentary
      parent: Abhisamayālaṃkāra
    8de86bfb66a54876a4cea8bfe1de566b:
      title: Prologue to Introduction to the Middle Way (Madhyamakāvatāra)
      parent: Madhyamakāvatāra
    5b5ac0eab702424f9c7428dae8c0d74c:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Secret Vajra Knot
    88763bed212d41cc9c76e4138aee84ee:
      title: 'A Garland of Fresh Utpala Flowers: A Brief Synopsis of the Treasury
        of Precious Qualities, A Treatise of Pith Instructions'
      parent: Treasury of Precious Qualities
    c32f5051279f47228497234636fced5b:
      title: 'Mirror of the Mind: Prologue to The Treasury of Precious Qualities'
      parent: Treasury of Precious Qualities
created_at: '2022-03-01T05:03:49.700105'
last_modified_at: '2022-03-01T05:03:49.700108'
statistics:
  total_words: 5414
  total_non_words: 468
quality:
  non_words_ratio: 0.09
